title: Introducción  a la Ingenieria de software 
iconURL: assets/default-icon.png
theme: Introducción a la Ingenieria de software
Autor :Samuel Valencia  
# for a clean 

permalink: :slug

social:
  twitter: _SupunKavinda
  github: SupunKavinda

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
